### ISSUE TITLE
Error in get(objname) : invalid first argument

### ISSUE THREAD

**Issue by MichaelFolkes** [mdlincoln/docthisaddin#2]
Hi Matthew,
Thanks for the addin.
I created a function:
    junk <- function(a,b){  paste(a,b) }
then sourced it. 
When I ran "Addins: document object"  I go the error:
Error in get(objname) : invalid first argument
What am I doing wrong?

**Comment by mdlincoln** [comment]
Make sure that you highlight the function name `junk` in the source editor before you run Addins -> Document object
